### ISSUE TITLE
ERROR `>` not supported between instances of `NoneType1 and `uind32`

### ISSUE THREAD

**Issue by SergeyKGoncharov** [ChainGreenOrg/chaingreen-blockchain#39] opened 2021-06-20 05:16 UTC
When this error is fixed. The third day the app is not syncing

**Comment by nflows** [comment] 2021-06-20 10:37
I think this project seems to be scam or idk... Nothing developed within this week. Horrible Fork

**Comment by miosukakura** [comment] 2021-06-20 23:09
@SergeyKGoncharov We will check what is going on. The same thing happening on one of our machines. 
@nflows check the github activity and let's talk then.

**Comment by miosukakura** [comment] 2021-06-20 23:10
This is a duplicate of #38 so I am closing the issue.

**Closed by miosukakura** 2021-06-20 23:10 UTC
Labels: duplicate
